### ISSUE TITLE
[signin_signup] Crud user : database, controller, routes

### ISSUE THREAD

**Issue by ghost** [pnc-virtual-company/2021-G9-VC2-PART2#1]
We create route to crud (create, read, update, delete) user account.

**Comment by sophannachhorn** [comment]
[Route_for_whole_project.docx](https://github.com/pnc-virtual-company/2021-G9-VC2-PART2/files/7743216/Route_for_whole_project.docx)
@ronanpnc Good afternoon teacher ! here is the file of routes for our project. Could you check it and give us feedback? Thank you
