### ISSUE TITLE
Sprint Review For Iteration One

### ISSUE THREAD

**Issue by ghost** [pnc-virtual-company/2021-G9-VC2-PART2#14]
Here is our sprint review for iteration one

**Comment by ghost** [comment]
@Sreypichly 
Dear Mrs. Sreypich,

Good evening Mrs. Sreypich, How are you doing? I hope you are doing well. I am writing this email for the purpose of sending my worklog that is related to the activity of my task in iteration one.
Here is the link to my document. 
[Worklog Template.xlsx](https://github.com/pnc-virtual-company/2021-G9-VC2-PART2/files/7761837/Worklog.Template.xlsx)
Thank you for your time.

Best regards,

SINET SEM

**Comment by prosnob** [comment]
@Sreypichly 
Dear Tutor. Sreypichly,

As I finished iteration one this morning. My team demoed what we have completed to you, project manager, and tutor.
So, I am writing this to send you a work log and reflection that I have done for a whole iteration one.
I have attached my file below. May you check and provide me feedbacks? I am willing to improve more for the next iteration from your feedback.

Best Regards, 

PROS NOB

[Pros-Nob-Worklog.xlsx](https://github.com/pnc-virtual-company/2021-G9-VC2-PART2/files/7761848/Pros-Nob-Worklog.xlsx)

**Comment by somphorsngoun** [comment]
@Sreypichly 
Dear Tutor. Sreypich,

Good evening, Teacher. How are you doing? I hope you are doing well.

After iteration one of the projects had finished and we had presented what we have already done to the customer, project manager, and tutor.
I also have done with my work log and reflection. So, I am writing this to send you my work log and reflection. I hope you will provide me with some feedback. I am waiting for your response. Thank you for your time.

Best Regards,

SOMPHORS NGOUN
[Somphors_Worklog_week1 .xlsx](https://github.com/pnc-virtual-company/2021-G9-VC2-PART2/files/7762840/Somphors_Worklog_week1.xlsx)

**Comment by sophannachhorn** [comment]
@Sreypichly 
Dear Totur. Sreypich,

As we already knew that iteration one is finished. we presented and demoed what we have done with iteration one about sign in, admin can invite alumni, and alumni can login to see their profile. In this iteration, I have learnt a lots and completed on my work log and reflection. So, I am writing this to send it to you. I hope you will available to check it and provide me some feedback. I am willing to learn from your feedback.

Best Regards,

SOPHANNA CHHORN
[sophanna.chhorn_worklog.xlsx](https://github.com/pnc-virtual-company/2021-G9-VC2-PART2/files/7763028/sophanna.chhorn_worklog.xlsx)

**Comment by VuthyWA** [comment]
@Sreypichly 

Dear Tutor. Sreypichly,

How are you so far? I hope you are doing well with your job. After I finished iteration one this morning. My team demoed what we have done to you, project manager, and customer.
So, I'm writing this message to send you a work log and reflection that I have done for iteration one.
I have attached my file below. Could you please check and provide me any feedbacks? I will improve more for the next iteration from your feedback.

Best Regards,

Vuthy YIB
[Vuthy Worklog Template.xlsx](https://github.com/pnc-virtual-company/2021-G9-VC2-PART2/files/7763565/Vuthy.Worklog.Template.xlsx)
