### ISSUE TITLE
Sprint planning for iteration 2

### ISSUE THREAD

**Issue by somphorsngoun** [pnc-virtual-company/2021-G9-VC2-PART2#17]

**Comment by somphorsngoun** [comment]
@ronanpnc 
Good evening teacher. How are you doing?
I'm writing this message to send you our sprint planning for iteration 2.
Could you help to check it?
Here it is:
1.	UX/UI improvement
       •	Change interface of alumni profile and design mockup for alumni view, explore alumni view 
2.	As an ALUMNI
        •	My Profile
                i.	Create dialog for edit data of user alumni
                ii.	Edit Profile information
                iii.	Edit Image profile of alumni
                iv.	CRUD alumni current employment.
3.	As an ERO OFFICER
        •	Explore alumni view 
                i.	Design a mock-up
                ii.	Search alumni
                iii.	Manage on filter alumni
4.	As an Admin
        •	Manage User
                i.	Design mockup
                ii.	Create dialog form Invite alumni
                iii.	Verify email before the invitation
                iv.	CRUD ERO OFFICER 
                v.      Create admin view in frontend and connect with backend 
5.	Manage role of user
       •	Manage permission accessible of Admin, Ero, Alumni.

**Comment by ronanpnc** [comment]
Hello @somphorsngoun  it's clear to me as objetives for V2
@Sethmok  are you ok with hotse obejctive for V2 ?

**Comment by Sethmok** [comment]
Hi @somphorsngoun @ronanpnc this is good for V2. Also, as we have just discussed, ERO account also has manage user in manu bar, and they can view/edit/remove alumni account only. Don't forget to send me final mock up if you have. Our meeting date for V2 will be the same and I will join online.
