### ISSUE TITLE
[admin&explore-alumni] Design mockup for manage user page and explore alumni page.

### ISSUE THREAD

**Issue by somphorsngoun** [pnc-virtual-company/2021-G9-VC2-PART2#23]
We work on UX/UI to design the interface for managing users and exploring alumni

**Comment by VuthyWA** [comment]
@Sethmok 

Dear Mr.Piseth
Here is the mock up interface for iteration 2; please check my mock up and give me any feedback if you have. 

[VC2-PART-2.pdf](https://github.com/pnc-virtual-company/2021-G9-VC2-PART2/files/7776624/VC2-PART-2.pdf)

Thank you for your time.

Best Regard, 

Vuthy YIB
