### ISSUE TITLE
[my_profile] add table and crud on the backend

### ISSUE THREAD

**Issue by somphorsngoun** [pnc-virtual-company/2021-G9-VC2-PART2#24]
+Add table and crud on :
    - company
    - position
    - work experience is association table of alumni, company, and position

**Comment by sophannachhorn** [comment]
@ronanpnc 
Good morning teacher ! How are you doing? I hope you are doing well. I'm writing this message, I would like to add new tables in ER_diagram. Could you help to check our ER_diagram? 
![image](https://user-images.githubusercontent.com/77522019/147305547-96b1b20d-aed8-4f0c-8842-9f4c1e94e47e.png)

Best Regards,

Sophanna CHHORN
