### ISSUE TITLE
Sprint Planning For Iteraion 3

### ISSUE THREAD

**Issue by prosnob** [pnc-virtual-company/2021-G9-VC2-PART2#29]
For ERO ADMIN, we will work on: 
-	[admin] We will connect backend to the fronted for user view 
-	[admin] We will improve to invite alumni faster.
-	[admin] We will manage accessibility of user for the application.
As an ERO OFFICER, we will work on: 
-	[EXPLORER ALUMNI] We will add advance filter with skill of alumni
As an ALUMNI, we will work on: 
-	[my-profile] We will manage skill of alumni in page my-profile
-	[my-profile] We will manage company for alumni (company have information like name, location, domain, photo, email/phone) 
For ADMIN,ERO,ALUMNI
-	[admin] We will change interface for page manager user view.
-	[my-profile] We will change interface for page my profile view.
-	[explore-alumni] We will change interface for page explore alumni view.
-	[admin] We will validate error all form in page manager user view.
-	[my-profile] We will validate error all form in page my profile view.
-	[explore-alumni] We will validate error all form in page explore alumni view.

**Comment by prosnob** [comment]
@ronanpnc 
@Sreypichly 
Dear Project Manager Ronan,

I have written some tasks that we are working on it in iteration 3.
Could you see and provide us some feedback?
The plan are listed below: 

For ERO ADMIN, we will work on: 
-	[admin] We will connect backend to the fronted for user view 
-	[admin] We will improve to invite alumni faster.
-	[admin] We will manage accessibility of user for the application.
For an ERO OFFICER, we will work on: 
-	[EXPLORER ALUMNI] We will add advance filter with skill of alumni
For an ALUMNI, we will work on: 
-	[my-profile] We will manage skill of alumni in page my-profile
-	[my-profile] We will manage company for alumni (company have information like name, location, domain, photo, email/phone) 
For ADMIN,ERO,ALUMNI
-	[admin] We will change interface for page manager user view.
-	[my-profile] We will change interface for page my profile view.
-	[explore-alumni] We will change interface for page explore alumni view.
-	[admin] We will validate error all form in page manager user view.
-	[my-profile] We will validate error all form in page my profile view.
-	[explore-alumni] We will validate error all form in page explore alumni view.

Best Regard,

PROS NOB

**Comment by ronanpnc** [comment]
Hello @prosnob 
Thx for the planning

Regarding the new interfaces , as discussed during the meeting, it's the first priority !

As soon as you have  designed new interaces, could you include them in the gitbub fro validation ?

thx !
