### ISSUE TITLE
Sprint Review For Iteration 2

### ISSUE THREAD

**Issue by prosnob** [pnc-virtual-company/2021-G9-VC2-PART2#35]
We had a meeting with customer, project manager, and tutor, so we are going to report about : 
- feedback from customer and project manager.
- what we  have done best.
- what we need to improve.
- And what we need to do for the next iteration.

**Comment by prosnob** [comment]
@Sreypichly 
Dear Tutor Sreypich,

I finished sprint review yesterday, so I am writing this email to send you my sprint review for iteration 2. 
The main points of this sprint review, I have listed down about : 
- Feedback from customer and project manager
- what we have done best
- what we commit to improve for the next iteration
- planning for the next iteration
File is attached below, you can check our sprint review and provide us feedback.
[SPRINT REVIEW-ITERATION2-G9.docx](https://github.com/pnc-virtual-company/2021-G9-VC2-PART2/files/7795070/SPRINT.REVIEW-ITERATION2-G9.docx)

Thank you for your time.

Best Regard,

PROS NOB

**Comment by ronanpnc** [comment]
Hello @prosnob 

I think regarding ""What we commit to improve for the next iteration?("

==> this is about soft SKILS not what you planned to do


For instance : one feedback for this team :   you should communicate more often regarding your mock up with your customer/PM  to avoid to have suprises during the sprint review !
