### ISSUE TITLE
[my_profile] Create Profile View For Alumni

### ISSUE THREAD

**Issue by ghost** [pnc-virtual-company/2021-G9-VC2-PART2#8]
We create interface profile view for the alumni.

**Comment by prosnob** [comment]
@ronanpnc 
@Sethmok 
Good morning, Teacher

Could you help to check for alumni_profile_view? I coded and pushed it.
And I also have attached interface of mockup below.
If you have any feedback please drop me here.
Thank you!
![image](https://user-images.githubusercontent.com/77546846/146853000-7c02c990-b53a-4ea0-9ea1-965c985d6fe6.png)
